### ISSUE TITLE
Add JSON string module

### ISSUE THREAD

**Issue by newswim** [jacob-alford/schemata-ts#11]

**Comment by jacob-alford** [comment]
The idea of a JSON string module is to guarantee that `JSON.parse` will succeed, and will come with a helper function to convert a JSONString type into an unknown type (as opposed to an Either Error unknown, or Option unknown).

**Comment by skeate** [comment]
should be its own thing in `Schemable` with this for the `Arbitrary` instance https://dubzzz.github.io/fast-check/functions/json.html

**Comment by jacob-alford** [comment]
Now I'm thinking this might be better as a `DecodeFromString` generic schemata, where you pass in a constrained decoder to decode a string value, parse it, and decode it using the supplied decoder.  Would be nice for 1.x

**Comment by jacob-alford** [comment]
Edit, this might need to be a schemable for arbitrary... `WithJsonDecode` or something

**Comment by jacob-alford** [comment]
I'm thinking this will be good to implement as two Schemables: `WithParser` with a `parseJson` schemable method; and `WithJson` with two schemable methods: `json`, and `jsonString`.  This can also include a schema `JsonFromString` which will `imap` a `JsonString` to `Json`.

Eventually we may consider expanding `WithParser` to have other things to parse like base 64

**Comment by jacob-alford** [comment]
I ended up determining that the json parser is better off as a Typeclass / interpreter.  See #221
