### ISSUE TITLE
Convert tenable string modules to schemas

### ISSUE THREAD

**Issue by jacob-alford** [jacob-alford/schemata-ts#126]
Using PatternBuilder we can now convert many of the string modules in `src / string` to be schemas in `src / schemas / string`.  Some of them will be very difficult, and I think we should save those for later.  This ticket is identifying the easy wins and converting those (along with the tests).

1. Identify string modules that are trivially convertable
2. Convert to schema along with test files (which should preferably remain the same to make sure nothing was lost in translation).

- [x] #139
- [x] #146
- [x] #144
- [x] #141
- [x] #148
- [x] #174
- [x] #150
- [x] #155
- [x] #156
- [x] #157
- [x] #175
- [x] #176
- [x] #177
- [x] #169
- [x] `IntString`
- [x] `NaturalString`
- [x] `NegativeFloatString`
- [x] `NegativeIntString`
- [x] `NonNegativeFloatString`
- [x] `NonPositiveFloatString`
- [x] `NonPositiveIntString`
- [x] `PositiveFloatString`
- [x] `PositiveIntString`

**Comment by skeate** [comment]
modules that can be converted (i.e. require nothing other than a regex to test):

- [ ] `Ascii`
- [ ] `BigIntString` (I think? the current implementation actually tries to build a `BigInt`)
- [ ] `BtcAddress`
- [ ] `EmailAddress`
- [ ] `HexColor`
- [ ] `HslColor`
- [ ] `IntString`
- [ ] `ISODataString` (I think)
- [ ] `JWT`
- [ ] `NaturalString`
- [ ] `NegativeFloatString`
- [ ] `NegativeIntString`
- [ ] `NonemptyString` (doesn't really need a `Pattern` though; a refinement should be plenty. no `Arbitrary` construction issues here)
- [ ] `NonNegativeFloatString`
- [ ] `NonPositiveFloatString`
- [ ] `NonPositiveIntString`
- [ ] `PositiveFloatString`
- [ ] `PositiveIntString`
- [ ] `RGB`
- [ ] `UUID`


modules that need something extra:
- `Base64[Url]` (need to determine length for padding `=`s)
- `CreditCard` (needs a Luhn checksum)

(I was expecting more of them to be problematic...)

**Comment by jacob-alford** [comment]
Oh yeah, that is pretty exhaustive.  I was accounting for credit cards, ISODateString, and other complicated Regexes being too much work to represent with pattern builder, because they're a couple miles long.  If they're doable too I say go for it.  The other's have some funky logic inside their guard, but I suppose with the right pattern, refine can do the trick.

**Comment by skeate** [comment]
checked off the ones that are done in #135

**Comment by jacob-alford** [comment]
I think we might convert bigIntString instead to a schemable bigIntFromString to match `intFromString`

**Comment by jacob-alford** [comment]
For ISOString, I think we might also convert that to a dateFromIsoString.  We can also convert safeDate to a Schema using refine + brand

**Comment by jacob-alford** [comment]
I'm going to add Base64 to the list and also do JWT at the same time, so I can use the same pattern combinators

**Comment by jacob-alford** [comment]
I was looking at the base64 module, and I'm thinking that it can be converted to a schema.

There's a `notBase64` regex character class, so we can just use the negation of that, combined with 0, 1, or 2 `=` at the end.  

We can also then use a refine to filter out strings which aren't divisible by 4.  That ought to be sufficient for all the instances I'm thinking

**Comment by skeate** [comment]
good idea. a little bit of churn in the arbitrary but not much

**Comment by jacob-alford** [comment]
We did it 🎉
