### ISSUE TITLE
Add Optic Derivation

### ISSUE THREAD

**Issue by jacob-alford** [jacob-alford/schemata-ts#134]
The idea for an optic schemable is to return prisms for sums, optional for nulls/undefined's, traversals for iterables, and lenses for products.  This ticket can be an investigative ticket, or an implementation ticket depending on how teneable adding it becomes

**Comment by skeate** [comment]
Do we _want_ this to be polymorphic? That sounds like a nightmare

**Comment by jacob-alford** [comment]
I'm just thinking that it might be necessary for a singular schemable instance to have a common interface, i.e. Lens / Prism / Optional / Traverse extends Optic.

**Comment by skeate** [comment]
Oh, generally "polymorphic lenses" refers to the ability to change the type of the focus, not combining all the different optic types into one big thing
