### ISSUE TITLE
Add `SetFromArray` generic schema

### ISSUE THREAD

**Issue by jacob-alford** [jacob-alford/schemata-ts#164]
This should be possible to make a schema using:

- Array
- imap

Should live in schemata/generic/SetFromArray

**Comment by skeate** [comment]
note: this would not obey `encode(decode(x)) == x`

it would however obey the weaker `encode(decode(encode(decode(x)))) == encode(decode(x))`

**Comment by jacob-alford** [comment]
Oh, good point

**Comment by jacob-alford** [comment]
I think I'm inclined to include it with a disclaimer in the comment that the schema does not produce lawful decoder and encoder instances
