### ISSUE TITLE
Convert schemable modules to `With` typeclasses

### ISSUE THREAD

**Issue by jacob-alford** [jacob-alford/schemata-ts#167]
Depends on #126

Convert the src modules in `string`, `number`, `generic` and `date` into files in a `schemables` folder.  And bring in `WithPattern`, `WithBrand`, and `WithInvariant` to match.  

Each schemable should have all its instances in the same file.  

These should be:

- [x] #179
- [x] #180
- [x] #181
- [x] #190
- [x] #182
- [x] #183
- [x] #185
- [x] #192
- [x] #193
- [x] #194

If it is possible to convert any of these to schemata, that is preferable.  Some are possible but should likely remain as schemables because of performance reasons, like mapFromEntries.

It is also necessary to adjust the auto-generation file to read from schemables (and extend the base Schemable typeclass).  It should greatly simplify the script.

**Comment by jacob-alford** [comment]
That should work as long as the Arbitrary instance isn't too bad.  When I added it, I was thinking about how only 1 in 4 base64s would pass, and how that could be more elegant.  But it's probably not all that bad

**Comment by skeate** [comment]
We can reduce it to one in 3: xdigit{2-4}+

**Comment by jacob-alford** [comment]
What if we add a WithPadding that has leftPad and rightPad that takes a number (modulus) and a character?

**Comment by skeate** [comment]
That's what I was originally thinking actually, but I went along with your suggestion since it's not too inefficient and no extra code

**Comment by jacob-alford** [comment]
I think I've changed my mind :P and really it depends on whoever wants to work on it.  But I don't think it'll be too bad

**Comment by jacob-alford** [comment]
In fact, let me try to get a PR up

**Comment by jacob-alford** [comment]
We did it :tada:
