### ISSUE TITLE
Fix branding

### ISSUE THREAD

**Issue by skeate** [jacob-alford/schemata-ts#170]
I think we have the branding a little backwards... We want the key to be a symbol, and the value can be anything that also has a symbol inside of it.

cf io-ts `Brand` https://github.com/gcanti/io-ts/blob/master/src/index.ts#L1132-L1162 which I think we should use.

This also lets us put metadata about the brand on it, if we so choose

**Comment by jacob-alford** [comment]
Sounds good to me!

**Comment by jacob-alford** [comment]
Would this also allow us to inject generic constraints, like min / max for int / float?

**Comment by skeate** [comment]
I think so? we can do something like

```ts
type MIN = -9007199254740991
type MAX = 9007199254740991
const MIN: MIN = -9007199254740991
const MAX: MAX = 9007199254740991

type IntBrand<Min extends number, Max extends number> = {
  readonly Int: unique symbol;
  readonly Min: Min;
  readonly Max: Max;
}

const Int: {
  (): SchemaExt<Branded<number, IntBrand<MIN, MAX>>>;
  <Min extends number>(min: Min): SchemaExt<Branded<number, IntBrand<Min, MAX>>>;
  <Min extends number, Max extends number>(min: Min, max: Max): SchemaExt<Branded<number, IntBrand<Min, Max>>>;
} = <Min extends number, Max extends number>(min?: Min = MIN, max?: Max = MAX) => make(s => pipe(
  s.int({ min, max }),
  s.brand<IntBrand<Min, Max>>(),
)
```

that's giving type errors in the definition because of the possibility of doing `Int<3, 4>(5, 6)`, but the declaration should make that a non-issue

might work better with real function overloading instead of that weird style

**Comment by jacob-alford** [comment]
It would be very nice not to have to have separate brands for the number variants!
