### ISSUE TITLE
Add Error Helpers

### ISSUE THREAD

**Issue by jacob-alford** [jacob-alford/schemata-ts#215]
It would be nice to have some error helpers to make mapping decode errors easier.  FreeSemigroup is a tree structure that's hard to work with.  So it'd be nice to have a `foldMap` helper that takes a monoid instance `M` and a function from `DecodeError -> M`.  And we can also re-export `DecodeError.fold`.  The complicated part is recursing through a FreeSemigroup using `FreeSemigroup.fold`.

**Comment by skeate** [comment]
There's [`draw`](https://github.com/gcanti/io-ts/blob/master/src/Decoder.ts#L607) in io-ts; why this code isn't in `DecodeError.ts` is a mystery though

**Comment by jacob-alford** [comment]
I think draw is good for debugging, but I can imagine a scenario when you'd need more than a one-size fits all.  One place where I've needed it before is returning 400 messages based on invalid request bodies, draw inserts a bunch of random characters that normally don't look good in a JSON object
