### ISSUE TITLE
[2.0] Remove Guard derivation, add Guard interpreter

### ISSUE THREAD

**Issue by jacob-alford** [jacob-alford/schemata-ts#239]
# 2.0

Guard prevents pure invariance, and can be expressed as an interpreter that wraps `Decoder`

**Comment by skeate** [comment]
Can you elaborate? I might be missing something, but 

> can be expressed as an interpreter that wraps `Decoder`

is the idea here "decode to `A`, and if it successfully decodes, it's an `A`"? if so, doesn't sound right, since our `Decoder` can change the structure. you can't use a `Decoder<A, B>` as a guard for the data type `B`

**Comment by jacob-alford** [comment]
The decoder is mappable, _but_ it's the output type that changes.  And guard guards for the input type.  

So if we were to express decoder / guard as HKT2s:

Decoder: 

```typescript
declare module 'fp-ts/lib/HKT' {
  interface URItoKind2<_E, A> {
    readonly Decoder: Decoder<unknown, A>
  }
```

Guard:

```typescript
declare module 'fp-ts/lib/HKT' {
  interface URItoKind2<E, _A> {
    readonly Guard: Guard<unknown, E>
  }
```

So the reason that Decoder is sufficient for Guard is because decoder first guarantees that and unknown is `E`, and then converts to `A`.

**Comment by jacob-alford** [comment]
And it follows that if decoder can decode to an `A` from unknown, it first had to decode successfully to `E`

**Comment by skeate** [comment]
I mean, that's not [how Guard works in io-ts right now](https://github.com/gcanti/io-ts/blob/master/src/Guard.ts#L23-L25)

**Comment by jacob-alford** [comment]
Yeah, it's a design decision.  And incidentally it won't affect any of the basal io-ts, because io-ts doesn't distinguish between the E and A types.  The only transformation schemables we have are dateFromString (which is kind of loosey goosey anyway), and `optionFromExclude` (which is itself a bit hard to use)

**Comment by skeate** [comment]
I think we should leave `Guard` as checking the domain type since, as noted here, the `Decoder` already works as an _input_ type check, and there'd be nothing to check if a value is already a domain type or not

**Comment by skeate** [comment]
Also don't forget we have the entire `WithInvariant` schemable

**Comment by jacob-alford** [comment]
Well the whole point would be for making schemable properly invariant.  I have an idea that I'll include here, but ultimately I think what we have is the most convenient way to provide guards for schemata based on transforms.  But let me know what you think of this idea, because I think it has some merit. 

HKT3 idea:

Make a Schemable3 based on Input type, Output type, and Transformed type.  So for all the basal schemables like `Int` or `Float` Guard (based on Output) would be the branded Int, or Float, and Decoder would be the same.  And for every transformed type Decoder and Encoder would both change, but Guard would remain fixed.

The upsides to this approach is that: 

1. Imap no longer requires a Guard to be passed in
2. We don't need Guard instances for every Schemable
3. Guard will still work great for all of our pattern schemata
4. Guards for _most_ transformed values are trivial anyway, like a guard for Option, or a guard for Date, or a guard for bigint.

The downside is that we would be providing many fewer in-house guards, which is essentially what we're doing for every transformation, and might be marginally more complicated when the type inside a guard matches the _per-transformed r_ type relative to decoder

**Comment by skeate** [comment]
- What is the difference between the "Output type" and the "Transformed type"?
- How does an HKT3 (a type-level construct) make `imap` not require a `Guard` anymore?

**Comment by jacob-alford** [comment]
The extra parameter would essentially track the pre-transformed type.   So for example, this could be the theoretical type-lambda for `Int` as an example:

```typescript
type Int = Branded<number, IntBrand>

export interface IntSchemable<S extends TypeLambda> {
  readonly int: Kind<S, number, never, Int, Int>
}
```

And the definition for Invariant would then be:

```typescript
export interface InvariantSchemable<S extends TypeLambda> {
  readonly imap: <A, B>(f: (a: A) => B, g: (b: B) => A) => <I, O>(self: Kind<S, I, never, O, A> => Kind<S, I, never, O, B>
}
```

And for every Schemable which hasn't been transformed will have an `O` parameter that's equal to the `A` parameter.

**Comment by jacob-alford** [comment]
Oh and the reason Guard won't need to be passed in is that all of the Guard derivations would be removed and the definition of Guard would be adjusted to use the pre-transformed type for which Decoder validly guards for.  And this would allow Guard to be derived from Decoder

**Comment by jacob-alford** [comment]
`G.Option(G.Int)`

**Comment by jacob-alford** [comment]
Because it really isn't valid to say `G.OptionFromUndefined(G.Int)` because you can't Imap a Guard.  And same for JsonSchema technically.  So it'd be more accurate to generate guards for pre-transformed values and same for JsonSchema

**Comment by jacob-alford** [comment]
But we could also provide manual guards for the output types, like Option, BigInt, Date, Map, etc.  It just wouldn't get injected into the derivation

**Comment by skeate** [comment]
Then you have two different schemas, which defeats the entire purpose of this library

**Comment by jacob-alford** [comment]
I mean if you prefer less accurate / valid representations of schemata then sure

**Comment by skeate** [comment]
I don't understand the problem with leaving `Guard` as a guard on the output type.

The main thing is you don't have a situation like `imap` requiring you to provide a guard because we can't derive one. But that's just _one_ example of a schemable instance which doesn't wholly support all possible `Schemable`s.

I think the solution there is not "let's just delete everything which can't support every possible feature" but "let's figure out a way to make it dynamic, with a fallback mechanism where possible". In the `imap` case, a fallback is possible: you provide your own `Guard`

That seems _far_ preferable to me than requiring users to make two schemas for data structures just to get a feature that _we already provide right now_.

**Comment by jacob-alford** [comment]
Fair enough.  I was just trying to push the idea as far as possible.  And I think Guard _should_ match Arbitrary, and Arbitrary is imappable.

I do want to keep pushing for JsonSchema using that _pre-transformed_ type though

**Comment by jacob-alford** [comment]
On the Arbitrary / Guard part, should Arbitrary make input types, or output types?  Because if endpoints (for example) operate on input types,  then the Arbitraries can't be used to test endpoints, because Arbitraries will have already generated the output type (which is not successfully decode)

**Comment by skeate** [comment]
Hm.

Going a step further ... Original `Schemable` was only ever free in one term. `Decoder` is technically a two-param type, but the first is constrained to always be `unknown`.

We now have a system of two _free_ parameters. It could be argued we might want any given instance from any given perspective.

In this view, with a `Schema<E, A>`, a `Decoder` is just a function `E -> A` but one that also handles `(not E) -> Error`. Similarly, an `Encoder` is `A -> E` (and the secondary case doesn't actually need to be handled because we never have a `(not A)`)

It's easy to argue that, in addition to  `Guard<A>`, we could also want `Guard<E>`. An `Arbitrary<E>` as well as an `Arbitrary<A>`

**Comment by jacob-alford** [comment]
That makes sense to me, it's also why Printer has `domainToJson` (encoder input to SafeJson) and `codomainToJson` (encoder output to Json) type, which for v2 I'm going to rename to `JsonPrinter` with `printInput` (output of encoder), and `printOutput` (input of encoder).  We could do the same thing with Guard and Arbitrary: 

```typescript
interface Guard<I, A> {
  readonly is: (a: unknown): a is A
  readonly isInput: (i: unknown) i is I
}

interface GuardTypeLambda extends TypeLambda {
  readonly type: Guard<this["in"], this["target"]>
}

interface Arbitrary<I, A> {
  readonly getOutputArbitrary: (a: typeof fc): fc.Arbitrary<A>
  readonly getInputArbitrary: (i: typeof fc): fc.Arbitrary<I>
}

interface ArbitraryTypeLambda extends TypeLambda {
  readonly type: Arbitrary<this["in"], this["target"]>
}

interface Decoder<A> {
  readonly decode: (i: unknown): E.Either<DecodeError, A>
}

interface DecoderTypeLambda extends TypeLambda {
  readonly type: Decoder<this["target"]>
}

interface Encoder<I, A> {
  readonly encode: (a: A): I
}

interface EncoderTypeLambda extends TypeLambda {
  readonly type: Encoder<this["In"], this["target"]>
}

type JsonSchema<O> = Const<JsonSchemaWithDescription, O>

interface JsonSchemaTypeLambda extends TypeLambda {
  readonly type: JsonSchema<this["Out1"]>
}

interface Schema<I, O, A> {
  <S extends TypeLambda>(schemable: Schemable<S>): Kind<S, I, never, O, A>
}
```

And the reason for the `O` parameter is to capture decoder values _before_ they've been `imap`d.  This is useful because they are stronger types (i.e. NaturalBrand vs number) than _just_ the input types.

**Comment by skeate** [comment]
I do still think `Decoder` should include a reference to the `A` type in the `Left`, but maybe it could just have both:

```ts
interface Decoder<I, A> {
  readonly decode: (i: unknown): E.Either<Const<DecodeError, [I, A]>, A>
}
```

The reason is that the `DecodeError` is structured relative to the `A` type and it'd be handy to have that around to create utility functions (e.g. some kind of matching on which fields errored, exactly.)

**Comment by jacob-alford** [comment]
Not a bad idea, we could have: 

```typescript
export interface DecodeErrorMeta<I,A> {
  readonly expectedInput: I
  readonly expectedOutput: A
}

export interface Decoder<I, A> {
  readonly decode: (i: unknown) => Either<Const<DecodeError, DecodeErrorMeta<I, A>>, A>
}
```

**Comment by jacob-alford** [comment]
Closing, domain guards are too valuable
