### ISSUE TITLE
[2.0] Spruce up Decoder

### ISSUE THREAD

**Issue by jacob-alford** [jacob-alford/schemata-ts#243]
# 2.0

With the new decode errors, and in-house decoder: convert Decoder to return a left of `Const<DecodeError, Input>` so the return error has reference to expected input type.  And this allows a Decoder to be an HKT2 that utilizes input type

**Comment by skeate** [comment]
wait, whoa

`Decoder`s should always be from `unknown`

if this is based on my discord message, I was saying the `Left` of a decoder should have a reference to the _output_ type.

**Comment by jacob-alford** [comment]
Agreed, Decoder should always decode from unknown, but it's unknown to an expected input.  My explanation in the Guard issue should tie these together

**Comment by jacob-alford** [comment]
In #239
