### ISSUE TITLE
Improve the `Base64` module

### ISSUE THREAD

**Issue by newswim** [jacob-alford/schemata-ts#45]
Discovery work while adding the `Base64` and `Base64Url` modules. See https://github.com/jacob-alford/schemable-ts-types/pull/40

Currently the `isBase64` guard only does a few simple checks. I'm concerned that it might not be exhaustive, but I'm also pretty new to the topic.

Here are a list of learning resources to use when the time comes:

- https://datatracker.ietf.org/doc/html/rfc4648
- https://developer.mozilla.org/en-US/docs/Glossary/Base64
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs
- https://base64.guru
-  https://rgxdb.com/r/1NUN74O6
- https://stackoverflow.com/questions/55389211/string-based-data-encoding-base64-vs-base64url
- https://stackoverflow.com/questions/475074/regex-to-parse-or-validate-base64-data/475217#475217
- https://en.wikipedia.org/wiki/Base64#Applications_not_compatible_with_RFC_4648_Base64

More resources related to Regex (because I have concerns about performance when using a regex to fully validate
- https://v8.dev/blog/non-backtracking-regexp
- https://medium.com/textmaster-engineering/performance-of-regular-expressions-81371f569698

**Comment by skeate** [comment]
honestly I feel like the existing `isBase64` is enough.

a regex that does the same thing, no additional checks needed, is `/^([A-Z0-9+/]{4}|[A-Z0-9+/]{3}=|[A-Z0-9+/]{2}==)$/i`

But we might also want to accept strings without the padding characters, since they aren't usually necessary

**Comment by skeate** [comment]
`Base64` schema seems pretty good to me, going to close this one
